# server configuration
server:
  host: "http://127.0.0.1"
  port: 8083

oauth:
  enabled: false
  trusted_issuers:
    - "http://localhost:8082/jwks"
    - "http://oauth.scorpio.ordinarycomputing.com:8082/jwks"

realm:
  name: "KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  password_rotation: "1h"
  password_length: 18

identities:
  principals:
    - scorpio/admin
  service_principals:
    - name: scorpio-oauth
      password: move-to-kube-secrets-1111
    - name: HTTP/ca.scorpio.ordinarycomputing.com
      password: move-to-kube-secrets-2222
    - name: scorpio-ui
      password: move-to-kube-secrets-3333
    - name: scorpio-kerberos
      password: move-to-kube-secrets-4444

# SPNEGO configurations
spnego:
  realm: "KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  service_principal_name: "scorpio-kerberos"
  password: "move-to-kube-secrets-4444"

# PKI configuration
pki:
  endpoint: "http://ca.scorpio.ordinarycomputing.com/spnego"
  service_principal_name: "HTTP/ca.scorpio.ordinarycomputing.com@KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  sans:
    - "krb.scorpio.ordinarycomputing.com"

# redis configurations
persistence:
  enabled: true
  host: "db-valkey-nyc1-scorpio-do-user-16782644-0.l.db.ondigitalocean.com"
  port: 25061
  user: "default"
  path: "/etc/scorpio-secret/password"
  database: 4
